# Generated by Django 4.2.8 on 2024-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Количество'),
        ),
    ]
