# Generated by Django 4.2.8 on 2024-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0002_alter_ingridient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
