# Generated by Django 4.2.8 on 2024-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingridient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='in_favorite_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Добавили в избранное'),
            preserve_default=False,
        ),
    ]
