# Generated by Django 4.2.8 on 2024-01-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_in_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='in_favorite_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Добавили в избранное'),
        ),
    ]
